coverage:
  status:
    project:
      default:
        informational: true
        # target: auto
        # https://docs.codecov.com/docs/common-recipe-list
        # adjust accordingly based on how flaky your tests are
        # this allows a 10% drop from the previous base commit coverage
        # threshold: 10%
    patch:
      default:
        informational: true
        # target: auto
        # threshold: 10%
