[build]
command = "npm run build"
publish = "out"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "@netlify/plugin-sitemap"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"
